### ISSUE TITLE
example always play 10000 messages 

### ISSUE THREAD

**Issue by hnaoto** [scribd/kafka-player#3]
The example script always play 10000 messages even if `num_of_messages` is changed to a different number

**Comment by xianwill** [comment]
@hnaoto - are you setting `num_messages` to a number greater or less than 10000? The example file only has 10k records in it, so this would be expected behavior if you are setting to a number greater. If you are setting a smaller number, this is a bug.

**Comment by xianwill** [comment]
@hnaoto  - I tested this locally and the `num_messages` cap works for me as expected.

**Comment by hnaoto** [comment]
hmmmm I have tried smaller number, it is sending 10000 messages....
